Add continuous deployment workflow 3

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -94,3 +94,9 @@ jobs:
       - name: Clean previous images and containers
         run: |
          docker system prune -f
+
+      - name: Debug ECR details
+        run: |
+         echo "Registry: ${{ steps.login-ecr.outputs.registry }}"
+         echo "Repo name: ${{ secrets.ECR_REPOSITORY_NAME }}"
+         aws ecr describe-repositories --repository-names ${{ secrets.ECR_REPOSITORY_NAME }} --region ${{ secrets.AWS_REGION }} || echo "Repo not found or no perms"
